// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAQBXn1T9lTT66KrBPwZb44-nfIK5D1E0',
    appId: '1:865495395091:web:3d320776c8749b844bc8e6',
    messagingSenderId: '865495395091',
    projectId: 'petadoption-1f4c1',
    authDomain: 'petadoption-1f4c1.firebaseapp.com',
    databaseURL: 'https://petadoption-1f4c1-default-rtdb.firebaseio.com',
    storageBucket: 'petadoption-1f4c1.firebasestorage.app',
    measurementId: 'G-S9EKWFSH51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY2MmfMxxva7DHP51m4Mst_KPhQUqMydY',
    appId: '1:865495395091:android:b2d141d187ab134f4bc8e6',
    messagingSenderId: '865495395091',
    projectId: 'petadoption-1f4c1',
    databaseURL: 'https://petadoption-1f4c1-default-rtdb.firebaseio.com',
    storageBucket: 'petadoption-1f4c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgVCk2gnkHSvBqWyqNDiPl0fBGi2RXP6Y',
    appId: '1:865495395091:ios:6516e1a3834b3f994bc8e6',
    messagingSenderId: '865495395091',
    projectId: 'petadoption-1f4c1',
    databaseURL: 'https://petadoption-1f4c1-default-rtdb.firebaseio.com',
    storageBucket: 'petadoption-1f4c1.firebasestorage.app',
    iosBundleId: 'com.example.petAdoption',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgVCk2gnkHSvBqWyqNDiPl0fBGi2RXP6Y',
    appId: '1:865495395091:ios:6516e1a3834b3f994bc8e6',
    messagingSenderId: '865495395091',
    projectId: 'petadoption-1f4c1',
    databaseURL: 'https://petadoption-1f4c1-default-rtdb.firebaseio.com',
    storageBucket: 'petadoption-1f4c1.firebasestorage.app',
    iosBundleId: 'com.example.petAdoption',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAQBXn1T9lTT66KrBPwZb44-nfIK5D1E0',
    appId: '1:865495395091:web:cc413051107196f84bc8e6',
    messagingSenderId: '865495395091',
    projectId: 'petadoption-1f4c1',
    authDomain: 'petadoption-1f4c1.firebaseapp.com',
    databaseURL: 'https://petadoption-1f4c1-default-rtdb.firebaseio.com',
    storageBucket: 'petadoption-1f4c1.firebasestorage.app',
    measurementId: 'G-Q01301WLL3',
  );
}
